dist: trusty
language: javascript
sudo: required

notifications:
    email: false

services:
    - docker

jobs:
  include:
    - stage: Cson Linting
      script:
        - docker run -tv ${PWD}:/coffeelint purplebabar/coffeelint */*.cson

    - stage: Atom Package Manager Publishing
      if: branch = master
      before_script:
        - npm install atom-package-manager
      script:
        - apm --version
