dist: trusty
language: node
sudo: required

notifications:
    email: false

services:
    - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsecret-1-dev

jobs:
  include:
    - stage: Cson Linting
      script:
        - docker run -tv ${PWD}:/coffeelint purplebabar/coffeelint */*.cson

    - stage: Atom Package Manager Publishing
      node_js: '8'
      if: branch = master
      before_script:
        - npm i atom-package-manager
      script:
        - apm --version
